# Generated by Django 6.0.4 on 2026-04-15 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('practitioners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('lab', "Résultat d'analyse"), ('imaging', 'Imagerie (radio, écho...)'), ('prescription', 'Ordonnance externe'), ('report', 'Compte-rendu médical'), ('other', 'Autre')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/')),
                ('document_date', models.DateField(blank=True, help_text="Date de l'examen", null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document médical',
                'verbose_name_plural': 'Documents médicaux',
                'db_table': 'medical_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnostic')),
                ('instructions', models.TextField(blank=True, help_text='Instructions générales')),
                ('follow_up_date', models.DateField(blank=True, help_text='Date de suivi recommandée', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_issued', to='practitioners.practitioner')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='Ex: 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='Ex: 2 fois par jour', max_length=100)),
                ('duration_days', models.PositiveSmallIntegerField(help_text='Durée du traitement en jours', validators=[django.core.validators.MinValueValidator(1)])),
                ('instructions', models.CharField(blank=True, help_text='Ex: Prendre après les repas', max_length=300)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.prescription')),
            ],
            options={
                'verbose_name': 'Médicament prescrit',
                'verbose_name_plural': 'Médicaments prescrits',
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Une fois par jour'), ('twice_daily', 'Deux fois par jour'), ('three_daily', 'Trois fois par jour'), ('every_8h', 'Toutes les 8 heures'), ('weekly', 'Une fois par semaine'), ('as_needed', 'Si besoin')], default='once_daily', max_length=20)),
                ('reminder_times', models.JSONField(default=list, help_text="Liste d'heures de rappel ex: ['08:00', '20:00']")),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL)),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='medical_records.prescriptionitem')),
            ],
            options={
                'verbose_name': 'Rappel médicament',
                'verbose_name_plural': 'Rappels médicaments',
                'db_table': 'medication_reminders',
                'ordering': ['medication_name'],
            },
        ),
    ]
