# Generated by Django 6.0.4 on 2026-04-15 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('in_person', 'En cabinet'), ('teleconsultation', 'Téléconsultation')], default='in_person', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Patient absent')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Motif de consultation indiqué par le patient')),
                ('patient_notes', models.TextField(blank=True, help_text='Notes complémentaires du patient')),
                ('practitioner_notes', models.TextField(blank=True, help_text='Observations du praticien (non visible par le patient)')),
                ('fee_at_booking', models.PositiveIntegerField(default=0, help_text='Tarif en FCFA au moment de la réservation')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='practitioners.practitioner')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='practitioners.timeslot')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'appointments',
                'ordering': ['-time_slot__date', '-time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_by', models.CharField(choices=[('patient', 'Patient'), ('practitioner', 'Praticien'), ('admin', 'Administrateur'), ('system', 'Système')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='appointments.appointment')),
                ('cancelled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annulation',
                'verbose_name_plural': 'Annulations',
                'db_table': 'appointment_cancellations',
            },
        ),
    ]
