# Generated by Django 6.0.4 on 2026-04-15 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(default='Cotonou', max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_open_sunday', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('active', 'Active'), ('suspended', 'Suspendue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'pharmacies',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnDutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='08:00', help_text='Fin de garde (peut être le lendemain)')),
                ('is_overnight', models.BooleanField(default=False, help_text='La garde se termine le lendemain matin')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'Pharmacie de garde',
                'verbose_name_plural': 'Pharmacies de garde',
                'db_table': 'on_duty_schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
