# Generated by Django 6.0.4 on 2026-04-15 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Dr., Pr., etc.', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('languages', models.CharField(blank=True, help_text='Langues séparées par des virgules (ex: Français,Fon,Anglais)', max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=1)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='practitioner_docs/')),
                ('cabinet_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(default='Cotonou', max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('consultation_fee', models.PositiveIntegerField(default=0, help_text='Tarif de consultation en FCFA')),
                ('teleconsultation_fee', models.PositiveIntegerField(default=0, help_text='Tarif téléconsultation en FCFA')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='practitioner_photos/')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Praticien',
                'verbose_name_plural': 'Praticiens',
                'db_table': 'practitioners',
                'ordering': ['-rating_average', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'practitioner_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nom icône Material Icons', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'db_table': 'specialties',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('booked', 'Réservé'), ('blocked', 'Bloqué')], default='available', max_length=20)),
                ('is_teleconsultation', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
                'db_table': 'time_slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30, help_text="Durée d'un créneau en minutes")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'db_table': 'working_hours',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
