# Generated by Django 6.0.4 on 2026-04-15 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_practitioners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitionerreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitionerreview',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='practitioners.specialty'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='practitioners.practitioner'),
        ),
        migrations.AlterUniqueTogether(
            name='practitionerreview',
            unique_together={('patient', 'practitioner')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('practitioner', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('practitioner', 'day_of_week')},
        ),
    ]
